version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
  features:
    build: ./features
    depends_on:
      - rabbitmq
    restart: always
  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - rabbitmq
      - features
  metric:
    build: ./metric
    depends_on:
      - rabbitmq
      - features
      - model
    restart: always
    volumes:
      - ./logs:/app/logs
  plot:
    build: ./plot
    depends_on:
      - rabbitmq
      - features
      - model
      - metric
    restart: always
    volumes:
      - ./logs:/app/logs